project_id = "xywmgradzlzrhuxnbbag"

[functions.admin-api]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.pm-send-otp]
verify_jwt = false

[functions.pm-verify-otp]
verify_jwt = false

[functions.pm-api]
verify_jwt = false

[functions.notify-pm-assignment]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.change-password]
verify_jwt = false
